# 1. Exploring the data 

In [1]:
import numpy as np 
import pandas as pd
import re

In [2]:
def open_file(path):
    myfile = open(path)
    print(myfile.read())

## Cleaning Episode VI

In [3]:
episodeVI = pd.read_csv(r"..\Project_4_Sentiment-Analysis-API\raw_data\SW_EpisodeVI.txt", 
                        delim_whitespace=True, names=["index","character","dialogue", "other", "other2", "other3", "other4", 
                                                      "other5", "other6", "other7"] ,header = None)

# creating a dataframe with the txt file, for some reason I had to create
# additional columns to store some values 

In [4]:
episodeVI[0:10] #displaying the data - I can see there is really Nan for most of them

index              character  \
0  character               dialogue   
1          1        SHUTTLE CAPTAIN   
2          2  DEATH STAR CONTROLLER   
3          3        SHUTTLE CAPTAIN   
4          4                OFFICER   
5          5               OPERATOR   
6          6              JERJERROD   
7          7                  VADER   
8          8              JERJERROD   
9          9                  VADER   

                                            dialogue other other2 other3  \
0                                                NaN   NaN    NaN    NaN   
1  Command station, this is ST 321. Code Clearanc...   NaN    NaN    NaN   
2  The security deflector shield will be deactiva...   NaN    NaN    NaN   
3                       We're starting our approach.   NaN    NaN    NaN   
4  Inform the commander that Lord Vader's shuttle...   NaN    NaN    NaN   
5                                          Yes, sir.   NaN    NaN    NaN   
6  Lord Vader, this is an unexpected pleasure.  W...   NaN    NaN    NaN   
7  You may dispense with the pleasantries, Comman...   NaN    NaN    NaN   
8  I assure you, Lord Vader, my men are working a...   NaN    NaN    NaN   
9      Perhaps I can find new ways to motivate them.   NaN    NaN    NaN   

  other4 other5 other6 other7  
0    NaN    NaN    NaN    NaN  
1    NaN    NaN    NaN    NaN  
2    NaN    NaN    NaN    NaN  
3    NaN    NaN    NaN    NaN  
4    NaN    NaN    NaN    NaN  
5    NaN    NaN    NaN    NaN  
6    NaN    NaN    NaN    NaN  
7    NaN    NaN    NaN    NaN  
8    NaN    NaN    NaN    NaN  
9    NaN    NaN    NaN    NaN

In [5]:
episodeVI["other2"].unique() #Ok now I know I have in column other 2 I have

array([nan, 'hardly'], dtype=object)

In [6]:
episodeVI[episodeVI["other"] == 'hardly'] 
#line 284 is the line that is crashing the entire ds

Empty DataFrame
Columns: [index, character, dialogue, other, other2, other3, other4, other5, other6, other7]
Index: []

In [7]:
episodeVI["dialogue"][284] = f' {episodeVI["dialogue"][284]} {episodeVI["other"][284]} {episodeVI["other2"][284]} {episodeVI["other3"][284]} {episodeVI["other4"][284]} {episodeVI["other5"][284]} {episodeVI["other6"][284]}'
episodeVI["dialogue"][284]

' \\Exciting\\" is hardly the word I would'

In [8]:
episodeVI["other"].unique() #Ok now I know I have in column other 2 I have

array([nan, 'welcome.\\""', 'is'], dtype=object)

In [9]:
episodeVI[episodeVI["other"] == 'welcome.\\""'] 


index character          dialogue        other other2 other3 other4  \
190   190      LEIA  He means \You're  welcome.\""    NaN    NaN    NaN   

    other5 other6 other7  
190    NaN    NaN    NaN

In [10]:
episodeVI["dialogue"][190] = f'{episodeVI["dialogue"][190]} {episodeVI["other"][190]}'
episodeVI["dialogue"][190]

'He means \\You\'re welcome.\\""'

In [11]:
def column_cleaning(episode,column_name):
    episode.drop([column_name], axis=1,inplace=True)
    return episode

In [12]:
episodeVI.head()

index              character  \
0  character               dialogue   
1          1        SHUTTLE CAPTAIN   
2          2  DEATH STAR CONTROLLER   
3          3        SHUTTLE CAPTAIN   
4          4                OFFICER   

                                            dialogue other other2 other3  \
0                                                NaN   NaN    NaN    NaN   
1  Command station, this is ST 321. Code Clearanc...   NaN    NaN    NaN   
2  The security deflector shield will be deactiva...   NaN    NaN    NaN   
3                       We're starting our approach.   NaN    NaN    NaN   
4  Inform the commander that Lord Vader's shuttle...   NaN    NaN    NaN   

  other4 other5 other6 other7  
0    NaN    NaN    NaN    NaN  
1    NaN    NaN    NaN    NaN  
2    NaN    NaN    NaN    NaN  
3    NaN    NaN    NaN    NaN  
4    NaN    NaN    NaN    NaN

In [13]:
column_cleaning(episodeVI,'other')
column_cleaning(episodeVI,'other2')
column_cleaning(episodeVI,'other3')
column_cleaning(episodeVI,'other4')
column_cleaning(episodeVI,'other5')
column_cleaning(episodeVI,'other6')
column_cleaning(episodeVI,'other7')

index              character  \
0    character               dialogue   
1            1        SHUTTLE CAPTAIN   
2            2  DEATH STAR CONTROLLER   
3            3        SHUTTLE CAPTAIN   
4            4                OFFICER   
..         ...                    ...   
670        670                  LANDO   
671        671                  WEDGE   
672        672                  LANDO   
673        673                    HAN   
674        674               THREEPIO   

                                              dialogue  
0                                                  NaN  
1    Command station, this is ST 321. Code Clearanc...  
2    The security deflector shield will be deactiva...  
3                         We're starting our approach.  
4    Inform the commander that Lord Vader's shuttle...  
..                                                 ...  
670       Wedge, I don't think we're going to make it.  
671        You'll make it. Just follow me Gold Leader.  
672  I promised to return his ship without a scratc...  
673                                           Lando...  
674                                       They did it!  

[675 rows x 3 columns]

In [14]:
episodeVI[0:10]

index              character  \
0  character               dialogue   
1          1        SHUTTLE CAPTAIN   
2          2  DEATH STAR CONTROLLER   
3          3        SHUTTLE CAPTAIN   
4          4                OFFICER   
5          5               OPERATOR   
6          6              JERJERROD   
7          7                  VADER   
8          8              JERJERROD   
9          9                  VADER   

                                            dialogue  
0                                                NaN  
1  Command station, this is ST 321. Code Clearanc...  
2  The security deflector shield will be deactiva...  
3                       We're starting our approach.  
4  Inform the commander that Lord Vader's shuttle...  
5                                          Yes, sir.  
6  Lord Vader, this is an unexpected pleasure.  W...  
7  You may dispense with the pleasantries, Comman...  
8  I assure you, Lord Vader, my men are working a...  
9      Perhaps I can find new ways to motivate them.

In [15]:
def final_df(episode, name):
    episode = episode.drop([0])
    episode.drop(['index'], axis = 1, inplace = True) 
    episode['episode'] = name
    return episode


In [16]:
episodeVI = final_df(episodeVI, 'episode VI')
episodeVI[0:10]

character                                           dialogue  \
1         SHUTTLE CAPTAIN  Command station, this is ST 321. Code Clearanc...   
2   DEATH STAR CONTROLLER  The security deflector shield will be deactiva...   
3         SHUTTLE CAPTAIN                       We're starting our approach.   
4                 OFFICER  Inform the commander that Lord Vader's shuttle...   
5                OPERATOR                                          Yes, sir.   
6               JERJERROD  Lord Vader, this is an unexpected pleasure.  W...   
7                   VADER  You may dispense with the pleasantries, Comman...   
8               JERJERROD  I assure you, Lord Vader, my men are working a...   
9                   VADER      Perhaps I can find new ways to motivate them.   
10              JERJERROD  I tell you, this station will be operational a...   

       episode  
1   episode VI  
2   episode VI  
3   episode VI  
4   episode VI  
5   episode VI  
6   episode VI  
7   episode VI  
8   episode VI  
9   episode VI  
10  episode VI

## Cleaning Episode IV

In [17]:
episodeIV = pd.read_csv(r"..\Project_4_Sentiment-Analysis-API\raw_data\SW_EpisodeIV.txt", 
                        delim_whitespace=True, names=["index","character","dialogue","other", "other2", "other3", "other4", "other5", "other6"] ,header = None)

In [18]:
episodeIV[0:10]

index character                                           dialogue  \
0  character  dialogue                                                NaN   
1          1  THREEPIO  Did you hear that?  They've shut down the main...   
2          2  THREEPIO                                      We're doomed!   
3          3  THREEPIO  There'll be no escape for the Princess this time.   
4          4  THREEPIO                                       What's that?   
5          5  THREEPIO  I should have known better than to trust the l...   
6          6      LUKE  Hurry up!  Come with me!  What are you waiting...   
7          7  THREEPIO                 Artoo! Artoo-Detoo, where are you?   
8          8  THREEPIO                     At last!  Where have you been?   
9          9  THREEPIO  They're heading in this direction. What are we...   

  other other2 other3 other4 other5 other6  
0   NaN    NaN    NaN    NaN    NaN    NaN  
1   NaN    NaN    NaN    NaN    NaN    NaN  
2   NaN    NaN    NaN    NaN    NaN    NaN  
3   NaN    NaN    NaN    NaN    NaN    NaN  
4   NaN    NaN    NaN    NaN    NaN    NaN  
5   NaN    NaN    NaN    NaN    NaN    NaN  
6   NaN    NaN    NaN    NaN    NaN    NaN  
7   NaN    NaN    NaN    NaN    NaN    NaN  
8   NaN    NaN    NaN    NaN    NaN    NaN  
9   NaN    NaN    NaN    NaN    NaN    NaN

In [19]:
episodeIV["other"].unique() #finding unique value

array([nan, 'found'], dtype=object)

In [20]:
episodeIV[episodeIV["other"] == 'found'] #in which line there is a unique value


index character                                        dialogue  other  \
554   554  THREEPIO  I'm afraid I'm not quite sure, sir. He says \I  found   

     other2 other3           other4   other5    other6  
554  her,\"    and  keepsrepeating,  \"She's  here.\""

In [21]:
episodeIV["dialogue"][554] = f'{episodeIV["dialogue"][554]} {episodeIV["other"][554]} {episodeIV["other2"][554]} {episodeIV["other3"][554]} {episodeIV["other4"][554]} {episodeIV["other5"][554]} {episodeIV["other"][554]} {episodeIV["other6"][554]}'
episodeIV["dialogue"][554]

'I\'m afraid I\'m not quite sure, sir. He says \\I found her,\\" and keepsrepeating, \\"She\'s found here.\\""'

In [22]:
column_cleaning(episodeIV,'other')
column_cleaning(episodeIV,'other2')
column_cleaning(episodeIV,'other3')
column_cleaning(episodeIV,'other4')
column_cleaning(episodeIV,'other5')
column_cleaning(episodeIV,'other6')

index   character                                           dialogue
0     character    dialogue                                                NaN
1             1    THREEPIO  Did you hear that?  They've shut down the main...
2             2    THREEPIO                                      We're doomed!
3             3    THREEPIO  There'll be no escape for the Princess this time.
4             4    THREEPIO                                       What's that?
...         ...         ...                                                ...
1006       1006        LUKE                                            Oh, no!
1007       1007    THREEPIO  Oh, my!  Artoo!  Can you hear me?  Say somethi...
1008       1008  TECHNICIAN               We'll get to work on him right away.
1009       1009    THREEPIO  You must repair him!  Sir, if any of my circui...
1010       1010        LUKE                                He'll be all right.

[1011 rows x 3 columns]

In [23]:
episodeIV = final_df(episodeIV, 'episode IV')
episodeIV[0:10]

character                                           dialogue     episode
1   THREEPIO  Did you hear that?  They've shut down the main...  episode IV
2   THREEPIO                                      We're doomed!  episode IV
3   THREEPIO  There'll be no escape for the Princess this time.  episode IV
4   THREEPIO                                       What's that?  episode IV
5   THREEPIO  I should have known better than to trust the l...  episode IV
6       LUKE  Hurry up!  Come with me!  What are you waiting...  episode IV
7   THREEPIO                 Artoo! Artoo-Detoo, where are you?  episode IV
8   THREEPIO                     At last!  Where have you been?  episode IV
9   THREEPIO  They're heading in this direction. What are we...  episode IV
10  THREEPIO                Wait a minute, where are you going?  episode IV

## Cleaning Episode V

In [24]:
episodeV = pd.read_csv(r"..\Project_4_Sentiment-Analysis-API\raw_data\SW_EpisodeV.txt", 
                        delim_whitespace=True, names=["index","character","dialogue", "other"] ,header = None)

In [25]:
episodeV[0:10]

index character                                           dialogue  \
0  character  dialogue                                                NaN   
1          1      LUKE  Echo Three to Echo Seven. Han, old buddy, do y...   
2          2       HAN                    Loud and clear, kid. What's up?   
3          3      LUKE  Well, I finished my circle. I don't pick up an...   
4          4       HAN  There isn't enough life on this ice cube to fi...   
5          5      LUKE  Right. I'll see you shortly. There's a meteori...   
6          6      LUKE  Hey, steady girl. What's the matter? You smell...   
7          7      LUKE                                            Aaargh!   
8          8       HAN                                            Chewie!   
9          9       HAN  All right, don't lose your temper. I'll come r...   

  other  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4   NaN  
5   NaN  
6   NaN  
7   NaN  
8   NaN  
9   NaN

In [26]:
episodeV["other"].unique() #finding unique value

array([nan, 'knows\\"?"'], dtype=object)

In [27]:
episodeV[episodeV["other"] == 'knows\\"?"']

index character                   dialogue      other
53    53       HAN  What do you mean, \nobody  knows\"?"

In [28]:
episodeV["dialogue"][53] = f'{episodeV["dialogue"][53]} {episodeV["other"][53]}'
episodeV["dialogue"][53]

'What do you mean, \\nobody knows\\"?"'

In [29]:
column_cleaning(episodeV,'other')

index character                                           dialogue
0    character  dialogue                                                NaN
1            1      LUKE  Echo Three to Echo Seven. Han, old buddy, do y...
2            2       HAN                    Loud and clear, kid. What's up?
3            3      LUKE  Well, I finished my circle. I don't pick up an...
4            4       HAN  There isn't enough life on this ice cube to fi...
..         ...       ...                                                ...
835        835      LUKE  I'll meet you at the rendezvous point on  Tato...
836        836     LANDO               Princess, we'll find Han. I promise.
837        837      LUKE           Chewie, I'll be waiting for your signal.
838        838      LUKE     Take care, you two. May the Force be with you.
839        839      LUKE                                                Ow!

[840 rows x 3 columns]

In [30]:
episodeV =final_df(episodeV, 'episode V')
episodeV.head()

character                                           dialogue    episode
1      LUKE  Echo Three to Echo Seven. Han, old buddy, do y...  episode V
2       HAN                    Loud and clear, kid. What's up?  episode V
3      LUKE  Well, I finished my circle. I don't pick up an...  episode V
4       HAN  There isn't enough life on this ice cube to fi...  episode V
5      LUKE  Right. I'll see you shortly. There's a meteori...  episode V

### Merging the 3 episode + Creating csv files

In [31]:
merged_data_final = pd.concat([episodeIV, episodeV, episodeVI])
merged_data_final

character                                           dialogue     episode
1    THREEPIO  Did you hear that?  They've shut down the main...  episode IV
2    THREEPIO                                      We're doomed!  episode IV
3    THREEPIO  There'll be no escape for the Princess this time.  episode IV
4    THREEPIO                                       What's that?  episode IV
5    THREEPIO  I should have known better than to trust the l...  episode IV
..        ...                                                ...         ...
670     LANDO       Wedge, I don't think we're going to make it.  episode VI
671     WEDGE        You'll make it. Just follow me Gold Leader.  episode VI
672     LANDO  I promised to return his ship without a scratc...  episode VI
673       HAN                                           Lando...  episode VI
674  THREEPIO                                       They did it!  episode VI

[2523 rows x 3 columns]

In [32]:
merged_data_final['dialogue'] = merged_data_final['dialogue'].str.replace('[^\w\s#@/:%.,_-]', '', regex=True, flags=re.UNICODE)

In [33]:
merged_data_final[0:10]

character                                           dialogue     episode
1   THREEPIO  Did you hear that  Theyve shut down the main r...  episode IV
2   THREEPIO                                        Were doomed  episode IV
3   THREEPIO   Therell be no escape for the Princess this time.  episode IV
4   THREEPIO                                         Whats that  episode IV
5   THREEPIO  I should have known better than to trust the l...  episode IV
6       LUKE  Hurry up  Come with me  What are you waiting f...  episode IV
7   THREEPIO                   Artoo Artoo-Detoo, where are you  episode IV
8   THREEPIO                       At last  Where have you been  episode IV
9   THREEPIO  Theyre heading in this direction. What are we ...  episode IV
10  THREEPIO                 Wait a minute, where are you going  episode IV

In [34]:
merged_data_final.to_csv("df_all_episodes.csv", index=False, encoding='utf-8')